# Generated by Django 3.0.1 on 2020-02-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='email',
            field=models.TextField(default='no'),
        ),
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='sms',
            field=models.TextField(default='no'),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_finished_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_status',
            field=models.TextField(default='Yet to be Completed'),
        ),
    ]
